import data from "@/content/projects.json";

export interface ProjectImage {
  src: string;
  w: number;
  h: number;
  blur: string;
  caption: string;
  group?: string;
  // Present only when this entry is a video clip. `src`/`w`/`h`/`blur` above
  // still describe the poster frame (generated by scripts/images.mjs the
  // same way a still's blur placeholder is) — `video.src` is the actual clip
  // to play, and can be a relative /work/<slug>/ path (self-hosted) or an
  // absolute URL (externally hosted) — the player doesn't care which.
  video?: { src: string; duration?: number };
}

export interface Project {
  slug: string;
  title: string;
  year: number | null;
  category: "projects" | "commercial" | "personal";
  client: string;
  role: string;
  description: string;
  cover: { src: string; focal?: string } | null;
  images: ProjectImage[];
  // Maps an images[].group key to the short text shown as that group's
  // section break on the project page. A plain string renders as text; an
  // object renders `text` as a link to `href` (e.g. the client's site).
  // Only needed for entries whose images span multiple distinct shoots
  // (e.g. Events & Fundraisers).
  groups?: Record<string, string | { text: string; href: string }>;
  // Booking section rendered after the image stack. Only Graduation
  // sets this — see "This page ends with booking" in docs/content-plan.md.
  booking?: ProjectBooking;
}

export interface ProjectBooking {
  packages: { name: string; price: string; detail?: string }[];
  testimonials: { quote: string; attribution: string }[];
  faq: { q: string; a: string }[];
  formHref: string;
}

// content/projects.json currently has every images[] empty, which collapses
// to a `never[]` element type under plain JSON-import inference — assert the
// real shape explicitly instead of relying on that inference.
export const projects = data as Project[];

export const FILTERS = ["ALL", "PROJECTS", "COMMERCIAL", "PERSONAL"] as const;
export type Filter = (typeof FILTERS)[number];

export function getCoverImage(project: Project): ProjectImage | null {
  if (!project.cover) return null;
  return (
    project.images.find((image) => image.src === project.cover?.src) ?? null
  );
}

export function filterProjects(filter: Filter) {
  // Entries with no images yet are unfinished — hide them from the index and
  // grid rather than render broken/empty tiles.
  const withImages = projects.filter((project) => project.images.length > 0);

  return filter === "ALL"
    ? withImages
    : withImages.filter((project) => project.category === filter.toLowerCase());
}
